version: '3.8'
services:
  proxy-core:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - TOR_ENABLED=true
      - AI_OPTIMIZATION=true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tor-relay:
    image: torproject/tor:latest
    network_mode: "service:proxy-core"
    volumes:
      - ./torrc:/etc/tor/torrc:ro

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
